### PR TITLE
updated depreciated react functions createClass and PropTypes

### PR DESCRIPTION
**Pull request by theodore-q**
Used the advised updates for React.createClass and React.PropTypes.
I also Linted The whole thing.
Now there is no javascript warning message and you will be able to use newer versions of react without issue.

### CODE REVIEW

**Comment by nathansmith** [comment]
Hmm. I use Standard JS linting, so the semi-colons actually would throw an error.

https://standardjs.com

I will incorporate the `CreateClass` changes at some point.

Thanks, I appreciate it.

**Comment by coreyleelarson** [comment]
Ah, I was just doing this! Thank you!

**Comment by nathansmith** [comment]
Sorry this took so long.

I just went ahead and made it ES6 `class` syntax, since that's what I am doing for the project I'm using it on now. I figure this is the ideal "React way" to do things now, and that `CreateClass` was just a stop-gap anyway.

I tagged it `1.2.0` to reflect the changes.

https://github.com/nathansmith/unsemantic/tree/1.2.0

**Comment by coreyleelarson** [comment]
Should these files be transpiled to ES5 prior to npm publish?

When building with Webpack/babel-loader, we ```exclude: /node_modules/``` as most packages are already transpiled. If we don't use this, we get a slew of errors.

**Pull request closed without merging**
